### ISSUE TITLE
Sphinx IPC error

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#183]
**  Test [speech_detection_sphinx_test_nao_wav_1_ch_yes_no] -- sequential#1  **
Unexpected result : [u'yes', u'no\nstopPython']

**Comment by klpanagi** [comment]
ROS error trace:

```shell
ERROR] [WallTime: 1449073436.361453] Error processing request: 'deutera\nstopPython'
['Traceback (most recent call last):\n', '  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/klpanagi/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_speech_detection_sphinx4/src/rapp_speech_detection_sphinx4/speech_recognition_sphinx4_handler_node.py", line 116, in handleSpeechRecognitionCallback\n    res = proc[\'sphinx\'].speechRecognitionBatch( req )\n', '  File "/home/klpanagi/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_speech_detection_sphinx4/src/rapp_speech_detection_sphinx4/speech_recognition_sphinx4.py", line 163, in speechRecognitionBatch\n    spee_res = self._speechRecognition(spee_req)\n', '  File "/home/klpanagi/rapp_platform/rapp-platform-catkin-ws/src/rapp-platform/rapp_speech_detection_sphinx4/src/rapp_speech_detection_sphinx4/speech_recognition_sphinx4.py", line 187, in _speechRecognition\n    res.words.append(self._word_mapping[word])\n', "KeyError: 'deutera\\nstopPython'\n"]
[ERROR] [WallTime: 1449073436.373149] [Client 4] [id: 8SnTfVPPVT] call_service ServiceException: service [/rapp/rapp_speech_detection_sphinx4/batch_speech_to_text] responded with an error: error processing request: 'deutera\nstopPython'
```
